[project]
name = "graph-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.20.3",
]

[dependency-groups]
dev = [
    "basedpyright>=1.29.1",
    "crosshair>=0.1.0.dev11",
    "ruff>=0.11.10",
]
